apiVersion: v1
kind: Namespace
metadata:
  name: broken-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crash-app
  namespace: broken-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crash
  template:
    metadata:
      labels:
        app: crash
    spec:
      containers:
        - name: app
          image: busybox:1.36
          command: ["sh", "-c", "exit 1"]
