apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: incident-lab
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
              name: http
          command:
            - /bin/sh
            - /mnt/lab/check-and-start.sh
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          volumeMounts:
            - name: lab-entrypoint
              mountPath: /mnt/lab
              readOnly: true
            - name: api-config
              mountPath: /config/mode
              subPath: mode
              readOnly: true
            - name: api-secret
              mountPath: /secret/token
              subPath: token
              readOnly: true
      volumes:
        - name: lab-entrypoint
          configMap:
            name: shop-api-entrypoint
            defaultMode: 0755
        - name: api-config
          configMap:
            name: shop-api-config
        - name: api-secret
          secret:
            secretName: shop-api-secret
